"""add_indexes_to_dokumen_and_activity_log

Revision ID: 15509555fc5f
Revises: d35af21538fa
Create Date: 2026-05-26 22:31:53.208772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15509555fc5f'
down_revision: Union[str, Sequence[str], None] = 'd35af21538fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dokumen_jenis'), ['jenis'], unique=False)
        batch_op.create_index(batch_op.f('ix_dokumen_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dokumen_status'))
        batch_op.drop_index(batch_op.f('ix_dokumen_jenis'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))

    # ### end Alembic commands ###
