"""initial schema snapshot

Revision ID: 821c346122d2
Revises: 
Create Date: 2026-05-25 22:29:29.576132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821c346122d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_berkas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_berkas', sa.String(length=50), nullable=False),
    sa.Column('npwp_9', sa.String(length=50), nullable=True),
    sa.Column('npwp', sa.String(length=50), nullable=True),
    sa.Column('npwp_16', sa.String(length=50), nullable=True),
    sa.Column('nitku', sa.String(length=50), nullable=True),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('isi_berkas', sa.Text(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('status_pinjam', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_berkas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_berkas_no_berkas'), ['no_berkas'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dokumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_berkas', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('nomor', sa.String(length=100), nullable=True),
    sa.Column('jenis', sa.String(length=100), nullable=True),
    sa.Column('tahun', sa.String(length=10), nullable=True),
    sa.Column('tanggal', sa.String(length=20), nullable=True),
    sa.Column('pemilik', sa.String(length=200), nullable=True),
    sa.Column('wadah', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('peminjam', sa.String(length=200), nullable=True),
    sa.Column('tanggal_pinjam', sa.String(length=20), nullable=True),
    sa.Column('tanggal_kembali', sa.String(length=20), nullable=True),
    sa.Column('keperluan', sa.String(length=300), nullable=True),
    sa.Column('file_scan', sa.String(length=200), nullable=True),
    sa.Column('batas_kembali', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['no_berkas'], ['data_berkas.no_berkas'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dokumen_no_berkas'), ['no_berkas'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dokumen_no_berkas'))

    op.drop_table('dokumen')
    op.drop_table('user')
    with op.batch_alter_table('data_berkas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_berkas_no_berkas'))

    op.drop_table('data_berkas')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
