"""Drop isi_berkas column

Revision ID: c04b774e563c
Revises: 821c346122d2
Create Date: 2026-05-26 09:20:11.485355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04b774e563c'
down_revision: Union[str, Sequence[str], None] = '821c346122d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('data_berkas', schema=None) as batch_op:
        batch_op.drop_column('isi_berkas')

    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('no_berkas',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('nama',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('nomor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'-'"))
        batch_op.alter_column('jenis',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'-'"))
        batch_op.alter_column('tahun',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'-'"))
        batch_op.alter_column('tanggal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('pemilik',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('wadah',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Di Gudang'"))
        batch_op.alter_column('peminjam',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_pinjam',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_kembali',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('keperluan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('file_scan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('batas_kembali',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_foreign_key('fk_dokumen_no_berkas_data_berkas', 'data_berkas', ['no_berkas'], ['no_berkas'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('batas_kembali',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('file_scan',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('keperluan',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_kembali',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_pinjam',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('peminjam',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Di Gudang'"))
        batch_op.alter_column('wadah',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('pemilik',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tahun',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'-'"))
        batch_op.alter_column('jenis',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'-'"))
        batch_op.alter_column('nomor',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'-'"))
        batch_op.alter_column('nama',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('no_berkas',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('data_berkas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isi_berkas', sa.TEXT(), nullable=True))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
