"""Ubah kolom tanggal jadi Date

Revision ID: d35af21538fa
Revises: c04b774e563c
Create Date: 2026-05-26 09:23:58.455881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35af21538fa'
down_revision: Union[str, Sequence[str], None] = 'c04b774e563c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.alter_column('tanggal',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_pinjam',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_kembali',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('batas_kembali',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.alter_column('batas_kembali',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_kembali',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal_pinjam',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tanggal',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
